base_url = "https://rustunit.com"
title = "rustunit"
description = "Rustunit offers software development consulting with a focus on rust, game-development and large scale distributed backend services."
compile_sass = true
build_search_index = false

[markdown]
highlight_code = true
highlight_theme = "material-dark"

[extra]
links = [
    # { title = "Rotterdam, NL", url = "https://maps.app.goo.gl/vYh2kSC4BPaJymXDA", icon = "location-dot" },
    { title = "LinkedIn", url = "https://www.linkedin.com/company/rustunit/", icon = "linkedin" },
    { title = "Contact", url = "/contact", icon = "mail" },
    { title = "GitHub", url = "https://github.com/rustunit", icon = "github" },
    { title = "YouTube", url = "https://www.youtube.com/@rustunit_com", icon = "youtube" },
    # { title = "Twitter", url = "https://twitter.com/rustunitcom", icon = "twitter" },
    { title = "Mastodon", url = "https://mastodon.social/@rustunit", icon = "mastodon" },
    { title = "Bsky", url = "https://bsky.app/profile/rustunit.com", icon = "bsky" },
    { title = "Discord", url = "https://discord.gg/rZv4uxSQx3", icon = "discord" },
]
